sudo: false
language: python
python:
  - '3.10'
  - '3.8'
  - '3.7'
env:
  - EVM_EMACS=emacs-git-snapshot-travis
matrix:
  include:
    - python: '3.8'
      env: EVM_EMACS=emacs-27.1-travis
    - python: '3.7'
      env: EVM_EMACS=emacs-27.1-travis
before_install:
  - pip install tox-travis tox-run-command

  # Install Emacs
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip        

  # Install Cask
  - curl -fsSkL
        --max-time 10
        --retry 10
        --retry-delay 10
        https://raw.github.com/cask/cask/master/go
        | python
  - export PATH="/home/travis/.cask/bin:$PATH"

  # The following command does (should) not have any effect on test,
  # but to separate installation phase and testing phase:
  - make before-test
script:
  - make travis-ci
